[env:esp32s3_sender]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -I../../../../packages/VaydeEngine/include

[env:esp32s3_mini_sender]
platform = espressif32@6.12.0
board = lolin_s3_mini
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -I../../../../packages/VaydeEngine/include

[env:esp32s3_zero_sender]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv

monitor_speed = 115200

build_flags =
    -std=gnu++17
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -I../../../../packages/VaydeEngine/include

[env:esp32c5_sender]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
board = esp32-c5-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags =
    -std=gnu++17
    -I../../../../packages/VaydeEngine/include
