[env:esp32c5_nrf24_receiver]
platform = espressif32
board = esp32-c5-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -DARDUINO_USB_CDC_ON_BOOT=0
lib_deps =
    nrf24/RF24@^1.6.1
