[env]
monitor_speed = 115200

[env:espnow_esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
build_flags =
    -std=gnu++17
    -DVAYDENET_BOARD_MODEL=\"ESP32-S3-DevKitC-1\"
    -DVAYDENET_ACTIVITY_LED_GPIO=48
    -DVAYDENET_ACTIVITY_LED_ADDRESSABLE=1

[env:espnow_esp32c5]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
board = esp32-c5-devkitc-1
framework = espidf
board_build.cmake_extra_args =
    -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig-c5.defaults"
build_flags =
    -std=gnu++17
    -DVAYDENET_BOARD_MODEL=\"ESP32-C5-DevKitC-1\"
    -DVAYDENET_ACTIVITY_LED_GPIO=27
    -DVAYDENET_ACTIVITY_LED_ADDRESSABLE=1

[env:esp32-s2]
platform = espressif32
board = esp32-s2-saola-1
framework = espidf
build_flags =
    -std=gnu++17
    -DVAYDENET_BOARD_MODEL=\"ESP32-S2-Flipper-WiFi-DevBoard\"
    -DVAYDENET_ACTIVITY_LED_GPIO=5
    -DVAYDENET_ACTIVITY_LED_ACTIVE_LOW_GPIO=1
